/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface Product {
  'id' : ProductId,
  'imageUrls' : Array<string>,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'category' : string,
  'price' : bigint,
  'points' : bigint,
}
export type ProductId = bigint;
export type RedemptionType = { 'mysteryBox' : string } |
  { 'cashback' : bigint };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<
    [string, bigint, string, string, bigint, Array<string>, bigint],
    ProductId
  >,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerPrincipal' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getPointsBalance' : ActorMethod<[], bigint>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAnyAdmin' : ActorMethod<[], boolean>,
  'isBootstrapAvailable' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[], undefined>,
  'redeemPoints' : ActorMethod<[RedemptionType], undefined>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'requestBootstrap' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleProductActive' : ActorMethod<[ProductId], undefined>,
  'updateProduct' : ActorMethod<
    [
      ProductId,
      string,
      bigint,
      string,
      string,
      bigint,
      Array<string>,
      boolean,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];